// Copyright (c) 2018-2018 Laurent Moussault. All rights reserved.
// Licensed under a simplified BSD license (see LICENSE file).

package input

import "github.com/cozely/cozely/internal"

var binders = map[string]binding{
	// Gamepad
	"Left Stick":         gpStick{},
	"Left Stick X":       gpStick{},
	"Left Stick Y":       gpStick{},
	"Right Stick":        gpStick{},
	"Right Stick X":      gpStick{},
	"Right Stick Y":      gpStick{},
	"Left Trigger":       gpTrigger{},
	"Right Trigger":      gpTrigger{},
	"Left Bumper":        &gpButton{button: internal.GamepadButtonLeftBumper},
	"Right Bumper":       &gpButton{button: internal.GamepadButtonRightBumper},
	"Left Stick Button":  &gpButton{button: internal.GamepadButtonLeftStick},
	"Right Stick Button": &gpButton{button: internal.GamepadButtonRightStick},
	"Dpad Up":            &gpButton{button: internal.GamepadButtonDpadUp},
	"Dpad Left":          &gpButton{button: internal.GamepadButtonDpadLeft},
	"Dpad Down":          &gpButton{button: internal.GamepadButtonDpadDown},
	"Dpad Right":         &gpButton{button: internal.GamepadButtonDpadRight},
	"Button Y":           &gpButton{button: internal.GamepadButtonY},
	"Button X":           &gpButton{button: internal.GamepadButtonX},
	"Button A":           &gpButton{button: internal.GamepadButtonA},
	"Button B":           &gpButton{button: internal.GamepadButtonB},
	"Button Back":        &gpButton{button: internal.GamepadButtonBack},
	"Button Start":       &gpButton{button: internal.GamepadButtonStart},
	"Button Guide":       &gpButton{button: internal.GamepadButtonGuide},
	// Mouse
	"Mouse":             msPosition{},
	"Mouse X":           msPosition{},
	"Mouse Y":           msPosition{},
	"Mouse Left":        &msButton{button: mouseLeft},
	"Mouse Middle":      &msButton{button: mouseMiddle},
	"Mouse Right":       &msButton{button: mouseRight},
	"Mouse Back":        &msButton{button: mouseBack},
	"Mouse Forward":     &msButton{button: mouseForward},
	"Mouse Button 6":    &msButton{button: mouse6},
	"Mouse Button 7":    &msButton{button: mouse7},
	"Mouse Button 8":    &msButton{button: mouse8},
	"Mouse Button 9":    &msButton{button: 9},
	"Mouse Button 10":   &msButton{button: 10},
	"Mouse Button 11":   &msButton{button: 11},
	"Mouse Button 12":   &msButton{button: 12},
	"Mouse Button 13":   &msButton{button: 13},
	"Mouse Button 14":   &msButton{button: 14},
	"Mouse Button 15":   &msButton{button: 15},
	"Mouse Button 16":   &msButton{button: 16},
	"Mouse Button 17":   &msButton{button: 17},
	"Mouse Button 18":   &msButton{button: 18},
	"Mouse Button 19":   &msButton{button: 19},
	"Mouse Button 20":   &msButton{button: 20},
	"Mouse Scroll Up":   &msButton{},
	"Mouse Scroll down": &msButton{},
	// keyboard
	"A":          &kbKey{keycode: keyA},
	"B":          &kbKey{keycode: keyB},
	"C":          &kbKey{keycode: keyC},
	"D":          &kbKey{keycode: keyD},
	"E":          &kbKey{keycode: keyE},
	"F":          &kbKey{keycode: keyF},
	"G":          &kbKey{keycode: keyG},
	"H":          &kbKey{keycode: keyH},
	"I":          &kbKey{keycode: keyI},
	"J":          &kbKey{keycode: keyJ},
	"K":          &kbKey{keycode: keyK},
	"L":          &kbKey{keycode: keyL},
	"M":          &kbKey{keycode: keyM},
	"N":          &kbKey{keycode: keyN},
	"O":          &kbKey{keycode: keyO},
	"P":          &kbKey{keycode: keyP},
	"Q":          &kbKey{keycode: keyQ},
	"R":          &kbKey{keycode: keyR},
	"S":          &kbKey{keycode: keyS},
	"T":          &kbKey{keycode: keyT},
	"U":          &kbKey{keycode: keyU},
	"V":          &kbKey{keycode: keyV},
	"W":          &kbKey{keycode: keyW},
	"X":          &kbKey{keycode: keyX},
	"Y":          &kbKey{keycode: keyY},
	"Z":          &kbKey{keycode: keyZ},
	"1":          &kbKey{keycode: key1},
	"2":          &kbKey{keycode: key2},
	"3":          &kbKey{keycode: key3},
	"4":          &kbKey{keycode: key4},
	"5":          &kbKey{keycode: key5},
	"6":          &kbKey{keycode: key6},
	"7":          &kbKey{keycode: key7},
	"8":          &kbKey{keycode: key8},
	"9":          &kbKey{keycode: key9},
	"0":          &kbKey{keycode: key0},
	"Up":         &kbKey{keycode: keyUp},
	"Left":       &kbKey{keycode: keyLeft},
	"Down":       &kbKey{keycode: keyDown},
	"Right":      &kbKey{keycode: keyRight},
	"Enter":      &kbKey{keycode: keyReturn},
	"Space":      &kbKey{keycode: keySpace},
	"Tab":        &kbKey{keycode: keyTab},
	"Escape":     &kbKey{keycode: keyEscape},
	"Left Shift": &kbKey{keycode: keyLShift},
}
