// Copyright (c) 2018-2018 Laurent Moussault. All rights reserved.
// Licensed under a simplified BSD license (see LICENSE file).

package input

var binders = map[string]binding{
	// Gamepad
	"Left Stick":    gpStick{},
	"Left Stick X":  gpStick{},
	"Left Stick Y":  gpStick{},
	"Right Stick":   gpStick{},
	"Right Stick X": gpStick{},
	"Right Stick Y": gpStick{},
	"Left Trigger":  gpTrigger{},
	"Right Trigger": gpTrigger{},
	"Left Bumper":   gpButton{},
	"Right Bumper":  gpButton{},
	"Dpad Up":       gpButton{},
	"Dpad Left":     gpButton{},
	"Dpad Down":     gpButton{},
	"Dpad Right":    gpButton{},
	"Button Y":      gpButton{},
	"Button X":      gpButton{},
	"Button A":      gpButton{},
	"Button B":      gpButton{},
	"Button Back":   gpButton{},
	"Button Start":  gpButton{},
	// Mouse
	"Mouse":             msPosition{},
	"Mouse X":           msPosition{},
	"Mouse Y":           msPosition{},
	"Mouse Left":        &msButton{button: MouseLeft},
	"Mouse Middle":      &msButton{button: MouseMiddle},
	"Mouse Right":       &msButton{button: MouseRight},
	"Mouse Back":        &msButton{button: MouseBack},
	"Mouse Forward":     &msButton{button: MouseForward},
	"Mouse Button 6":    &msButton{button: Mouse6},
	"Mouse Button 7":    &msButton{button: Mouse7},
	"Mouse Button 8":    &msButton{button: Mouse8},
	"Mouse Button 9":    &msButton{button: 9},
	"Mouse Button 10":   &msButton{button: 10},
	"Mouse Button 11":   &msButton{button: 11},
	"Mouse Button 12":   &msButton{button: 12},
	"Mouse Button 13":   &msButton{button: 13},
	"Mouse Button 14":   &msButton{button: 14},
	"Mouse Button 15":   &msButton{button: 15},
	"Mouse Button 16":   &msButton{button: 16},
	"Mouse Button 17":   &msButton{button: 17},
	"Mouse Button 18":   &msButton{button: 18},
	"Mouse Button 19":   &msButton{button: 19},
	"Mouse Button 20":   &msButton{button: 20},
	"Mouse Scroll Up":   &msButton{},
	"Mouse Scroll down": &msButton{},
	// Keyboard
	"A":      &kbKey{keycode: KeyA},
	"B":      &kbKey{keycode: KeyB},
	"C":      &kbKey{keycode: KeyC},
	"D":      &kbKey{keycode: KeyD},
	"E":      &kbKey{keycode: KeyE},
	"F":      &kbKey{keycode: KeyF},
	"G":      &kbKey{keycode: KeyG},
	"H":      &kbKey{keycode: KeyH},
	"I":      &kbKey{keycode: KeyI},
	"J":      &kbKey{keycode: KeyJ},
	"K":      &kbKey{keycode: KeyK},
	"L":      &kbKey{keycode: KeyL},
	"M":      &kbKey{keycode: KeyM},
	"N":      &kbKey{keycode: KeyN},
	"O":      &kbKey{keycode: KeyO},
	"P":      &kbKey{keycode: KeyP},
	"Q":      &kbKey{keycode: KeyQ},
	"R":      &kbKey{keycode: KeyR},
	"S":      &kbKey{keycode: KeyS},
	"T":      &kbKey{keycode: KeyT},
	"U":      &kbKey{keycode: KeyU},
	"V":      &kbKey{keycode: KeyV},
	"W":      &kbKey{keycode: KeyW},
	"X":      &kbKey{keycode: KeyX},
	"Y":      &kbKey{keycode: KeyY},
	"Z":      &kbKey{keycode: KeyZ},
	"Up":     &kbKey{keycode: KeyUp},
	"Left":   &kbKey{keycode: KeyLeft},
	"Down":   &kbKey{keycode: KeyDown},
	"Right":  &kbKey{keycode: KeyRight},
	"Enter":  &kbKey{keycode: KeyReturn},
	"Space":  &kbKey{keycode: KeySpace},
	"Tab":    &kbKey{keycode: KeyTab},
	"Escape": &kbKey{keycode: KeyEscape},
}
