// Copyright (c) 2018-2018 Laurent Moussault. All rights reserved.
// Licensed under a simplified BSD license (see LICENSE file).

package input

import "github.com/cozely/cozely/internal"

var binders = map[string]source{
	// Gamepad
	"Left Stick":         &gpStick{xaxis: internal.GamepadLeftX, yaxis: internal.GamepadLeftY},
	"Left Stick X":       &gpAxis{axis: internal.GamepadLeftX},
	"Left Stick Y":       &gpAxis{axis: internal.GamepadLeftY},
	"Right Stick":        &gpStick{xaxis: internal.GamepadRightX, yaxis: internal.GamepadRightY},
	"Right Stick X":      &gpAxis{axis: internal.GamepadRightX},
	"Right Stick Y":      &gpAxis{axis: internal.GamepadRightY},
	"Left Trigger":       &gpTrigger{axis: internal.GamepadLeftTrigger},
	"Right Trigger":      &gpTrigger{axis: internal.GamepadRightTrigger},
	"Left Bumper":        &gpButton{button: internal.GamepadLeftBumper},
	"Right Bumper":       &gpButton{button: internal.GamepadRightBumper},
	"Left Stick Button":  &gpButton{button: internal.GamepadLeftClick},
	"Right Stick Button": &gpButton{button: internal.GamepadRightClick},
	"Dpad Up":            &gpButton{button: internal.GamepadDpadUp},
	"Dpad Left":          &gpButton{button: internal.GamepadDpadLeft},
	"Dpad Down":          &gpButton{button: internal.GamepadDpadDown},
	"Dpad Right":         &gpButton{button: internal.GamepadDpadRight},
	"Button Y":           &gpButton{button: internal.GamepadY},
	"Button X":           &gpButton{button: internal.GamepadX},
	"Button A":           &gpButton{button: internal.GamepadA},
	"Button B":           &gpButton{button: internal.GamepadB},
	"Button Back":        &gpButton{button: internal.GamepadBack},
	"Button Start":       &gpButton{button: internal.GamepadStart},
	"Button Guide":       &gpButton{button: internal.GamepadGuide},
	// Mouse
	"Mouse":              &msCoord{},
	"Mouse X":            &msAxis{},
	"Mouse Y":            &msAxis{},
	"Mouse Left":         &msButton{button: mouseLeft},
	"Mouse Middle":       &msButton{button: mouseMiddle},
	"Mouse Right":        &msButton{button: mouseRight},
	"Mouse Back":         &msButton{button: mouseBack},
	"Mouse Forward":      &msButton{button: mouseForward},
	"Mouse Button 6":     &msButton{button: mouse6},
	"Mouse Button 7":     &msButton{button: mouse7},
	"Mouse Button 8":     &msButton{button: mouse8},
	"Mouse Button 9":     &msButton{button: 9},
	"Mouse Button 10":    &msButton{button: 10},
	"Mouse Button 11":    &msButton{button: 11},
	"Mouse Button 12":    &msButton{button: 12},
	"Mouse Button 13":    &msButton{button: 13},
	"Mouse Button 14":    &msButton{button: 14},
	"Mouse Button 15":    &msButton{button: 15},
	"Mouse Button 16":    &msButton{button: 16},
	"Mouse Button 17":    &msButton{button: 17},
	"Mouse Button 18":    &msButton{button: 18},
	"Mouse Button 19":    &msButton{button: 19},
	"Mouse Button 20":    &msButton{button: 20},
	"Mouse Scroll Up":    &msWheel{direction: mouseScrollUp},
	"Mouse Scroll down":  &msWheel{direction: mouseScrollDown},
	"Mouse Scroll Left":  &msWheel{direction: mouseScrollLeft},
	"Mouse Scroll Right": &msWheel{direction: mouseScrollRight},
	// keyboard
	"A":          &kbKey{keycode: keyA},
	"B":          &kbKey{keycode: keyB},
	"C":          &kbKey{keycode: keyC},
	"D":          &kbKey{keycode: keyD},
	"E":          &kbKey{keycode: keyE},
	"F":          &kbKey{keycode: keyF},
	"G":          &kbKey{keycode: keyG},
	"H":          &kbKey{keycode: keyH},
	"I":          &kbKey{keycode: keyI},
	"J":          &kbKey{keycode: keyJ},
	"K":          &kbKey{keycode: keyK},
	"L":          &kbKey{keycode: keyL},
	"M":          &kbKey{keycode: keyM},
	"N":          &kbKey{keycode: keyN},
	"O":          &kbKey{keycode: keyO},
	"P":          &kbKey{keycode: keyP},
	"Q":          &kbKey{keycode: keyQ},
	"R":          &kbKey{keycode: keyR},
	"S":          &kbKey{keycode: keyS},
	"T":          &kbKey{keycode: keyT},
	"U":          &kbKey{keycode: keyU},
	"V":          &kbKey{keycode: keyV},
	"W":          &kbKey{keycode: keyW},
	"X":          &kbKey{keycode: keyX},
	"Y":          &kbKey{keycode: keyY},
	"Z":          &kbKey{keycode: keyZ},
	"1":          &kbKey{keycode: key1},
	"2":          &kbKey{keycode: key2},
	"3":          &kbKey{keycode: key3},
	"4":          &kbKey{keycode: key4},
	"5":          &kbKey{keycode: key5},
	"6":          &kbKey{keycode: key6},
	"7":          &kbKey{keycode: key7},
	"8":          &kbKey{keycode: key8},
	"9":          &kbKey{keycode: key9},
	"0":          &kbKey{keycode: key0},
	"Up":         &kbKey{keycode: keyUp},
	"Left":       &kbKey{keycode: keyLeft},
	"Down":       &kbKey{keycode: keyDown},
	"Right":      &kbKey{keycode: keyRight},
	"Enter":      &kbKey{keycode: keyReturn},
	"Space":      &kbKey{keycode: keySpace},
	"Tab":        &kbKey{keycode: keyTab},
	"Escape":     &kbKey{keycode: keyEscape},
	"Left Shift": &kbKey{keycode: keyLShift},
}
