// Copyright (c) 2013-2017 Laurent Moussault. All rights reserved.
// Licensed under a simplified BSD license (see LICENSE file).

package key

//------------------------------------------------------------------------------

import (
	"github.com/drakmaniso/carol/internal/core"
)

//------------------------------------------------------------------------------

// A Label designate a key by its label in the current layout of the keyboard.
// For printable characters, the value is the rune that would be generated by
// pressing the key without any modifiers.
type Label = core.KeyLabel

// Label constants
const (
	LabelUnknown Label = 0

	LabelReturn     Label = '\r'
	LabelEscape     Label = '\033' //FIXME
	LabelBackspace  Label = '\b'
	LabelTab        Label = '\t'
	LabelSpace      Label = ' '
	LabelExclaim    Label = '!'
	LabelQuoteDbl   Label = '"'
	LabelHash       Label = '#'
	LabelPercent    Label = '%'
	LabelDollar     Label = '$'
	LabelAmpersand  Label = '&'
	LabelQuote      Label = '\''
	LabelLeftParen  Label = '('
	LabelRightParen Label = ')'
	LabelAsterisk   Label = '*'
	LabelPlus       Label = '+'
	LabelComma      Label = ','
	LabelMinus      Label = '-'
	LabelPeriod     Label = '.'
	LabelSlash      Label = '/'
	Label0          Label = '0'
	Label1          Label = '1'
	Label2          Label = '2'
	Label3          Label = '3'
	Label4          Label = '4'
	Label5          Label = '5'
	Label6          Label = '6'
	Label7          Label = '7'
	Label8          Label = '8'
	Label9          Label = '9'
	LabelColon      Label = ':'
	LabelSemicolon  Label = ';'
	LabelLess       Label = '<'
	LabelEquals     Label = '='
	LabelGreater    Label = '>'
	LabelQuestion   Label = '?'
	LabelAt         Label = '@'

	// Skip uppercase letters

	LabelLeftBracket  Label = '['
	LabelBackSlash    Label = '\\'
	LabelRightBracket Label = ']'
	LabelCaret        Label = '^'
	LabelUnderscore   Label = '_'
	LabelBackQuote    Label = '`'
	LabelA            Label = 'a'
	LabelB            Label = 'b'
	LabelC            Label = 'c'
	LabelD            Label = 'd'
	LabelE            Label = 'e'
	LabelF            Label = 'f'
	LabelG            Label = 'g'
	LabelH            Label = 'h'
	LabelI            Label = 'i'
	LabelJ            Label = 'j'
	LabelK            Label = 'k'
	LabelL            Label = 'l'
	LabelM            Label = 'm'
	LabelN            Label = 'n'
	LabelO            Label = 'o'
	LabelP            Label = 'p'
	LabelQ            Label = 'q'
	LabelR            Label = 'r'
	LabelS            Label = 's'
	LabelT            Label = 't'
	LabelU            Label = 'u'
	LabelV            Label = 'v'
	LabelW            Label = 'w'
	LabelX            Label = 'x'
	LabelY            Label = 'y'
	LabelZ            Label = 'z'

	LabelCapsLock Label = unprintable | Label(PositionCapsLock)

	LabelF1  Label = unprintable | Label(PositionF1)
	LabelF2  Label = unprintable | Label(PositionF2)
	LabelF3  Label = unprintable | Label(PositionF3)
	LabelF4  Label = unprintable | Label(PositionF4)
	LabelF5  Label = unprintable | Label(PositionF5)
	LabelF6  Label = unprintable | Label(PositionF6)
	LabelF7  Label = unprintable | Label(PositionF7)
	LabelF8  Label = unprintable | Label(PositionF8)
	LabelF9  Label = unprintable | Label(PositionF9)
	LabelF10 Label = unprintable | Label(PositionF10)
	LabelF11 Label = unprintable | Label(PositionF11)
	LabelF12 Label = unprintable | Label(PositionF12)

	LabelPrintScreen Label = unprintable | Label(PositionPrintScreen)
	LabelScrollLock  Label = unprintable | Label(PositionScrollLock)
	LabelPause       Label = unprintable | Label(PositionPause)
	LabelInsert      Label = unprintable | Label(PositionInsert)
	LabelHome        Label = unprintable | Label(PositionHome)
	LabelPageUp      Label = unprintable | Label(PositionPageUp)
	LabelDelete      Label = '\177' //FIXME
	LabelEnd         Label = unprintable | Label(PositionEnd)
	LabelPageDown    Label = unprintable | Label(PositionPageDown)
	LabelRight       Label = unprintable | Label(PositionRight)
	LabelLeft        Label = unprintable | Label(PositionLeft)
	LabelDown        Label = unprintable | Label(PositionDown)
	LabelUp          Label = unprintable | Label(PositionUp)

	LabelNumLockClear Label = unprintable | Label(PositionNumLockClear)
	LabelKPDivide     Label = unprintable | Label(PositionKPDivide)
	LabelKPMultiply   Label = unprintable | Label(PositionKPMultiply)
	LabelKPMinus      Label = unprintable | Label(PositionKPMinus)
	LabelKPPlus       Label = unprintable | Label(PositionKPPlus)
	LabelKPEnter      Label = unprintable | Label(PositionKPEnter)
	LabelKP1          Label = unprintable | Label(PositionKP1)
	LabelKP2          Label = unprintable | Label(PositionKP2)
	LabelKP3          Label = unprintable | Label(PositionKP3)
	LabelKP4          Label = unprintable | Label(PositionKP4)
	LabelKP5          Label = unprintable | Label(PositionKP5)
	LabelKP6          Label = unprintable | Label(PositionKP6)
	LabelKP7          Label = unprintable | Label(PositionKP7)
	LabelKP8          Label = unprintable | Label(PositionKP8)
	LabelKP9          Label = unprintable | Label(PositionKP9)
	LabelKP0          Label = unprintable | Label(PositionKP0)
	LabelKPPeriod     Label = unprintable | Label(PositionKPPeriod)

	LabelApplication   Label = unprintable | Label(PositionApplication)
	LabelPower         Label = unprintable | Label(PositionPower)
	LabelKPEquals      Label = unprintable | Label(PositionKPEquals)
	LabelF13           Label = unprintable | Label(PositionF13)
	LabelF14           Label = unprintable | Label(PositionF14)
	LabelF15           Label = unprintable | Label(PositionF15)
	LabelF16           Label = unprintable | Label(PositionF16)
	LabelF17           Label = unprintable | Label(PositionF17)
	LabelF18           Label = unprintable | Label(PositionF18)
	LabelF19           Label = unprintable | Label(PositionF19)
	LabelF20           Label = unprintable | Label(PositionF20)
	LabelF21           Label = unprintable | Label(PositionF21)
	LabelF22           Label = unprintable | Label(PositionF22)
	LabelF23           Label = unprintable | Label(PositionF23)
	LabelF24           Label = unprintable | Label(PositionF24)
	LabelExecute       Label = unprintable | Label(PositionExecute)
	LabelHelp          Label = unprintable | Label(PositionHelp)
	LabelMenu          Label = unprintable | Label(PositionMenu)
	LabelSelect        Label = unprintable | Label(PositionSelect)
	LabelStop          Label = unprintable | Label(PositionStop)
	LabelAgain         Label = unprintable | Label(PositionAgain)
	LabelUndo          Label = unprintable | Label(PositionUndo)
	LabelCut           Label = unprintable | Label(PositionCut)
	LabelCopy          Label = unprintable | Label(PositionCopy)
	LabelPaste         Label = unprintable | Label(PositionPaste)
	LabelFind          Label = unprintable | Label(PositionFind)
	LabelMute          Label = unprintable | Label(PositionMute)
	LabelVolumeUp      Label = unprintable | Label(PositionVolumeUp)
	LabelVolumeDown    Label = unprintable | Label(PositionVolumeDown)
	LabelKPComma       Label = unprintable | Label(PositionKPComma)
	LabelKPEqualsAS400 Label = unprintable | Label(PositionKPEqualsAS400)

	LabelAltErase   Label = unprintable | Label(PositionAltErase)
	LabelSysReq     Label = unprintable | Label(PositionSysReq)
	LabelCancel     Label = unprintable | Label(PositionCancel)
	LabelClear      Label = unprintable | Label(PositionClear)
	LabelPrior      Label = unprintable | Label(PositionPrior)
	LabelReturn2    Label = unprintable | Label(PositionReturn2)
	LabelSeparator  Label = unprintable | Label(PositionSeparator)
	LabelOut        Label = unprintable | Label(PositionOut)
	LabelOper       Label = unprintable | Label(PositionOper)
	LabelClearAgain Label = unprintable | Label(PositionClearAgain)
	LabelCrSel      Label = unprintable | Label(PositionCrSel)
	LabelExSel      Label = unprintable | Label(PositionExSel)

	LabelKP00               Label = unprintable | Label(PositionKP00)
	LabelKP000              Label = unprintable | Label(PositionKP000)
	LabelThousandsSeparator Label = unprintable | Label(PositionThousandsSeparator)
	LabelDecimalSeparator   Label = unprintable | Label(PositionDecimalSeparator)
	LabelCurrencyUnit       Label = unprintable | Label(PositionCurrencyUnit)
	LabelCurrencySubUnit    Label = unprintable | Label(PositionCurrencySubUnit)
	LabelKPLeftParen        Label = unprintable | Label(PositionKPLeftParen)
	LabelKPRightParen       Label = unprintable | Label(PositionKPRightParen)
	LabelKPLeftBrace        Label = unprintable | Label(PositionKPLeftBrace)
	LabelKPRightBrace       Label = unprintable | Label(PositionKPRightBrace)
	LabelKPTab              Label = unprintable | Label(PositionKPTab)
	LabelKPBackspace        Label = unprintable | Label(PositionKPBackspace)
	LabelKPA                Label = unprintable | Label(PositionKPA)
	LabelKPB                Label = unprintable | Label(PositionKPB)
	LabelKPC                Label = unprintable | Label(PositionKPC)
	LabelKPD                Label = unprintable | Label(PositionKPD)
	LabelKPE                Label = unprintable | Label(PositionKPE)
	LabelKPF                Label = unprintable | Label(PositionKPF)
	LabelKPXor              Label = unprintable | Label(PositionKPXor)
	LabelKPPower            Label = unprintable | Label(PositionKPPower)
	LabelKPPercent          Label = unprintable | Label(PositionKPPercent)
	LabelKPLess             Label = unprintable | Label(PositionKPLess)
	LabelKPGreater          Label = unprintable | Label(PositionKPGreater)
	LabelKPAmpersand        Label = unprintable | Label(PositionKPAmpersand)
	LabelKPDblAmpersand     Label = unprintable | Label(PositionKPDblAmpersand)
	LabelKPVerticalBar      Label = unprintable | Label(PositionKPVerticalBar)
	LabelKPDblVerticalBar   Label = unprintable | Label(PositionKPDblVerticalBar)
	LabelKPColon            Label = unprintable | Label(PositionKPColon)
	LabelKPHash             Label = unprintable | Label(PositionKPHash)
	LabelKPSpace            Label = unprintable | Label(PositionKPSpace)
	LabelKPAt               Label = unprintable | Label(PositionKPAt)
	LabelKPExclam           Label = unprintable | Label(PositionKPExclam)
	LabelKPMemStore         Label = unprintable | Label(PositionKPMemStore)
	LabelKPMemRecall        Label = unprintable | Label(PositionKPMemRecall)
	LabelKPMemClear         Label = unprintable | Label(PositionKPMemClear)
	LabelKPMemAdd           Label = unprintable | Label(PositionKPMemAdd)
	LabelKPMemSubtract      Label = unprintable | Label(PositionKPMemSubtract)
	LabelKPMemMultiply      Label = unprintable | Label(PositionKPMemMultiply)
	LabelKPMemDivide        Label = unprintable | Label(PositionKPMemDivide)
	LabelKPPlusMinus        Label = unprintable | Label(PositionKPPlusMinus)
	LabelKPClear            Label = unprintable | Label(PositionKPClear)
	LabelKPClearEntry       Label = unprintable | Label(PositionKPClearEntry)
	LabelKPBinary           Label = unprintable | Label(PositionKPBinary)
	LabelKPOctal            Label = unprintable | Label(PositionKPOctal)
	LabelKPDecimal          Label = unprintable | Label(PositionKPDecimal)
	LabelKPHexadecimal      Label = unprintable | Label(PositionKPHexadecimal)

	LabelLCtrl  Label = unprintable | Label(PositionLCtrl)
	LabelLShift Label = unprintable | Label(PositionLShift)
	LabelLAlt   Label = unprintable | Label(PositionLAlt)
	LabelLGUI   Label = unprintable | Label(PositionLGUI)
	LabelRCtrl  Label = unprintable | Label(PositionRCtrl)
	LabelRShift Label = unprintable | Label(PositionRShift)
	LabelRAlt   Label = unprintable | Label(PositionRAlt)
	LabelRGUI   Label = unprintable | Label(PositionRGUI)

	LabelMode Label = unprintable | Label(PositionMode)

	LabelAudioNext   Label = unprintable | Label(PositionAudioNext)
	LabelAudioPrev   Label = unprintable | Label(PositionAudioPrev)
	LabelAudioStop   Label = unprintable | Label(PositionAudioStop)
	LabelAudioPlay   Label = unprintable | Label(PositionAudioPlay)
	LabelAudioMute   Label = unprintable | Label(PositionAudioMute)
	LabelMediaSelect Label = unprintable | Label(PositionMediaSelect)
	LabelWWW         Label = unprintable | Label(PositionWWW)
	LabelMail        Label = unprintable | Label(PositionMail)
	LabelCalculator  Label = unprintable | Label(PositionCalculator)
	LabelComputer    Label = unprintable | Label(PositionComputer)
	LabelACSearch    Label = unprintable | Label(PositionACSearch)
	LabelACHome      Label = unprintable | Label(PositionACHome)
	LabelACBack      Label = unprintable | Label(PositionACBack)
	LabelACForward   Label = unprintable | Label(PositionACForward)
	LabelACStop      Label = unprintable | Label(PositionACStop)
	LabelACRefresh   Label = unprintable | Label(PositionACRefresh)
	LabelACBookmarks Label = unprintable | Label(PositionACBookmarks)

	LabelBrightnessDown Label = unprintable | Label(PositionBrightnessDown)
	LabelBrightnessUp   Label = unprintable | Label(PositionBrightnessUp)
	LabelDisplaySwitch  Label = unprintable | Label(PositionDisplaySwitch)
	LabelKbdIllumToggle Label = unprintable | Label(PositionKbdIllumToggle)
	LabelKbdIllumDown   Label = unprintable | Label(PositionKbdIllumDown)
	LabelKbdIllumUp     Label = unprintable | Label(PositionKbdIllumUp)
	LabelEject          Label = unprintable | Label(PositionEject)
	LabelSleep          Label = unprintable | Label(PositionSleep)
)

const unprintable = 1 << 30

//------------------------------------------------------------------------------
